version: "3.8"

services:
  gab-apache:
    build:
      args:
        container_project_path: /var/www/html/
        uid: 1000
        user: $USER
      context: .
      dockerfile: ./Dockerfile
    image: bagisto-php-apache
    ports:
      - 80:80
    volumes:
      - ./workspace/:/var/www/html/
    restart: unless-stopped

  gab-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./.configs/mysql-data:/var/lib/mysql
    restart: unless-stopped

  gab-redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.configs/redis-data:/data
    restart: unless-stopped

  gab-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: gab-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - 8080:80
    restart: unless-stopped

  gab-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./.configs/elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  gab-kibana:
    image: docker.elastic.co/kibana/kibana:latest
    environment:
      - ELASTICSEARCH_HOSTS=http://bag-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - gab-elasticsearch
    restart: unless-stopped

  gab-mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025   
      - 8025:8025  
    restart: unless-stopped
