name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts' # This will use the latest LTS version of Node.js

    - name: Set permissions and run install script
      run: |
        chmod +x gab-app/scripts/install.sh
        ./gab-app/scripts/install.sh

    - name: Build and run Docker containers
      run: |
        cd gab-app
        docker-compose build && docker-compose up -d
